package com.thy.fss.common.inmemory.specification;

import com.thy.fss.common.inmemory.specification.attribute.MetaAttribute;

/**
 * Base interface for all generated StaticSpecificationService implementations.
 * Provides a central validation layer for both Specification and Filter structures.
 * <p>
 * This interface defines the contract that all generated specification services must implement.
 * Each entity class annotated with @MetaModel will have its own implementation generated
 * at build time by the annotation processor.
 *
 * @param <T> The entity type this service validates
 */
public interface SpecificationService<T> {

    /**
     * Validates an entity against a specification using meta attribute and operator.
     * This method serves as a bridge between Specification structures and the specific
     * validation methods generated for each field-operator combination.
     *
     * @param entity    The entity to validate
     * @param attribute The meta attribute representing the field
     * @param operator  The operator to apply
     * @param value     The value to compare against
     * @return true if the entity matches the specification, false otherwise
     * @throws UnsupportedOperationException if the attribute-operator combination is not supported
     */
    boolean validateSpecification(T entity, MetaAttribute<T, ?> attribute, Operator operator, Object value);

    /**
     * Validates an entity against a filter object.
     * This method serves as a bridge between Filter structures and the specific
     * validation methods generated for each field type.
     * <p>
     * The implementation should check all non-null filter criteria and return false
     * if any criterion fails. All criteria are combined with AND logic.
     *
     * @param entity The entity to validate
     * @param filter The filter object containing the criteria
     * @return true if the entity matches all filter criteria, false otherwise
     */
    boolean validateFilter(T entity, Object filter);

    /**
     * Gets the entity class this service validates.
     *
     * @return The entity class
     */
    Class<T> getEntityClass();

    /**
     * Creates a new instance of the entity class.
     * This method provides entity-specific instance creation logic without external dependencies.
     * Each StaticSpecificationService implements this for its own entity type.
     *
     * @return A new instance of the entity
     * @throws Exception if instance creation fails
     */
    T createInstance() throws Exception;


    /**
     * Extracts field value from an entity using field name.
     * This method is generated at build time and provides efficient field access
     * without reflection. Each StaticSpecificationService implements this for its own entity fields.
     *
     * @param entity    The entity to extract value from
     * @param fieldName The name of the field to extract
     * @return The field value, or null if field is null or not found
     * @throws UnsupportedOperationException if the field name is not supported by this entity
     */
    Object getFieldValue(T entity, String fieldName);

    /**
     * Extracts field value from an entity using meta attribute.
     * Provides type-safe field access using compile-time validated meta attributes.
     *
     * <p>This method is automatically generated by the StaticSpecificationService generator
     * based on the entity's field structure. It uses direct getter method calls instead of
     * reflection for type safety and performance.</p>
     * <p>
     * Generated Implementation Details:
     * <ul>
     *   <li>Simple fields: Direct getter method calls (entity.getName())</li>
     *   <li>Nested fields: Chained getter calls with null-safe navigation</li>
     *   <li>Collections: Access to collection properties, not individual elements</li>
     *   <li>Validation: Compile-time field validation through switch statements</li>
     * </ul>
     *
     * @param entity        The entity to extract value from
     * @param metaAttribute The meta attribute representing the field
     * @return The field value, or null if field is null
     * @throws UnsupportedOperationException if the meta attribute is not supported by this entity
     */
    Object getFieldValue(T entity, MetaAttribute<?, ?> metaAttribute);


    /**
     * Sets field value on an entity using meta attribute.
     * Provides type-safe field modification using compile-time validated meta attributes.
     * This method is preferred over string-based field access for performance and type safety.
     *
     * <p>This method is automatically generated by the StaticSpecificationService generator
     * based on the entity's field structure. It uses direct setter method calls instead of
     * reflection for type safety and performance.</p>
     *
     * @param entity        The entity to modify
     * @param metaAttribute The meta attribute representing the field to set
     * @param value         The value to set
     * @throws UnsupportedOperationException if the meta attribute is not supported by this entity
     */
    void setFieldValue(T entity, MetaAttribute<?, ?> metaAttribute, Object value);

    // ==================== SORTING METHODS ====================


    /**
     * Creates a comparator for sorting entities by a single field using field name.
     * This method is generated at build time and provides efficient field-specific sorting
     * without reflection. Each StaticSpecificationService implements this for its own entity fields.
     *
     * @param fieldName The name of the field to sort by
     * @param ascending true for ascending order, false for descending
     * @return A comparator for sorting entities by the specified field
     * @throws UnsupportedOperationException if the field name is not supported by this entity
     */
    java.util.Comparator<T> createComparator(String fieldName, boolean ascending);

    /**
     * Creates a comparator for sorting entities by a single field using meta attribute.
     * Provides type-safe field access for sorting operations.
     *
     * <p>For nested field access, each StaticSpecificationService handles its own fields
     * and delegates to sub-services for nested field navigation.</p>
     *
     * @param metaAttribute The meta attribute representing the field to sort by
     * @param ascending     true for ascending order, false for descending
     * @return A comparator for sorting entities
     * @throws UnsupportedOperationException if the meta attribute is not supported
     */
    java.util.Comparator<T> createComparator(MetaAttribute<?, ?> metaAttribute, boolean ascending);


    /**
     * Creates a multi-field comparator for sorting entities by multiple fields using field names.
     * This method is generated at build time and provides efficient multi-field sorting
     * without reflection. Each StaticSpecificationService implements this for its own entity fields.
     *
     * @param fieldNames     List of field names to sort by (in order of priority)
     * @param ascendingFlags List of ascending flags corresponding to each field name
     * @return A comparator for sorting entities by multiple fields
     * @throws IllegalArgumentException      if fieldNames and ascendingFlags have different sizes
     * @throws UnsupportedOperationException if any field name is not supported by this entity
     */
    java.util.Comparator<T> createMultiFieldComparator(
            java.util.List<String> fieldNames, java.util.List<Boolean> ascendingFlags);

    /**
     * Creates a multi-field comparator for sorting entities by multiple fields using meta attributes.
     * Provides type-safe field access for multi-field sorting operations.
     *
     * @param metaAttributes List of meta attributes representing the fields to sort by (in order of priority)
     * @param ascendingFlags List of ascending flags corresponding to each meta attribute
     * @return A comparator for sorting entities by multiple fields
     * @throws IllegalArgumentException      if metaAttributes and ascendingFlags have different sizes
     * @throws UnsupportedOperationException if any meta attribute is not supported
     */
    java.util.Comparator<T> createMultiFieldComparatorWithMetaAttributes(
            java.util.List<MetaAttribute<?, ?>> metaAttributes, java.util.List<Boolean> ascendingFlags);

    // ==================== COLLECTION METHODS ====================

    /**
     * Extracts value(s) from a collection based on the specified selector.
     * Supports ALL, FIRST, LAST, and ANY collection operations.
     *
     * @param collection The collection to extract from
     * @param selector   The collection selector (ALL, FIRST, LAST, ANY)
     * @return The extracted value(s) - can be a single element or a collection depending on selector
     */
    Object extractFromCollection(java.util.Collection<?> collection, com.thy.fss.common.inmemory.engine.mapping.CollectionSelector selector);

    /**
     * Gets the size of a collection.
     *
     * @param collection The collection to get size from
     * @return The size of the collection, or 0 if collection is null
     */
    int getCollectionSize(java.util.Collection<?> collection);

    /**
     * Checks if a collection is empty.
     *
     * @param collection The collection to check
     * @return true if collection is null or empty, false otherwise
     */
    boolean isCollectionEmpty(java.util.Collection<?> collection);

    // ==================== PATH-BASED FIELD ACCESS ====================

    /**
     * Gets a value from an entity using a path of MetaAttributes.
     * Supports nested properties by navigating through the object graph.
     *
     * <p>For nested paths, this method navigates through each MetaAttribute:
     * <ul>
     *   <li>Simple field: [name] → entity.getName()</li>
     *   <li>Nested field: [address, city] → entity.getAddress().getCity()</li>
     *   <li>Deep nested: [order, customer, address, city] → entity.getOrder().getCustomer().getAddress().getCity()</li>
     * </ul>
     *
     * @param entity The entity to get the value from
     * @param path   The path to the field (list of MetaAttribute objects)
     * @return The field value, or null if any intermediate value is null
     */
    Object getValueByPath(T entity, java.util.List<MetaAttribute<?, ?>> path);

    /**
     * Sets a value on an entity using a path of MetaAttributes.
     * Supports nested properties by navigating through the object graph.
     *
     * <p>For nested paths, this method navigates to the parent and sets the final field:
     * <ul>
     *   <li>Simple field: [name] → entity.setName(value)</li>
     *   <li>Nested field: [address, city] → entity.getAddress().setCity(value)</li>
     *   <li>Deep nested: [order, customer, name] → entity.getOrder().getCustomer().setName(value)</li>
     * </ul>
     *
     * @param entity The entity to set the value on
     * @param path   The path to the field (list of MetaAttribute objects)
     * @param value  The value to set
     * @throws IllegalStateException if any intermediate value in the path is null
     */
    void setValueByPath(T entity, java.util.List<MetaAttribute<?, ?>> path, Object value);

    // ==================== COLLECTION OPERATIONS WITH SPECIFICATIONS ====================

    /**
     * Extracts value(s) from a collection with specification filtering.
     * Filters the collection using the specification, then applies the selector.
     * Generated at build time for type-safe collection operations.
     *
     * <p>This method provides specification-based filtering for collection operations:
     * <ul>
     *   <li>If specification is null, applies selector to entire collection</li>
     *   <li>If specification is provided, filters collection first using validateSpecification()</li>
     *   <li>Then applies the selector (ALL, FIRST, LAST, ANY) to filtered results</li>
     * </ul>
     *
     * <p>Selector behavior:
     * <ul>
     *   <li>ALL: Returns filtered collection (or entire collection if no specification)</li>
     *   <li>FIRST: Returns first element from filtered collection (or null if empty)</li>
     *   <li>LAST: Returns last element from filtered collection (or null if empty)</li>
     *   <li>ANY: Returns any element from filtered collection (or null if empty)</li>
     * </ul>
     *
     * @param collection    The collection to extract from
     * @param selector      The collection selector (ALL, FIRST, LAST, ANY)
     * @param specification The specification to filter elements (can be null for no filtering)
     * @return The extracted value(s) after filtering and selection
     */
    Object extractFromCollection(
            java.util.Collection<T> collection,
            com.thy.fss.common.inmemory.engine.mapping.CollectionSelector selector,
            Specification<T> specification
    );

    /**
     * Gets a value from an entity using a path that may contain collection operations.
     * Navigates through the path, handling both regular fields and collection operations.
     * Generated at build time with direct method calls (no reflection).
     * Type-safe: uses generic CollectionOperationMetadata for element type safety.
     *
     * <p>This method processes paths with collection operations:
     * <ul>
     *   <li>Iterates through path elements (MetaAttribute objects)</li>
     *   <li>For each element, checks if there's a collection operation at that index</li>
     *   <li>If collection operation exists, applies it using extractFromCollection()</li>
     *   <li>If no collection operation, uses getFieldValue() for regular field access</li>
     *   <li>Handles null values with null-safe navigation (returns null if any intermediate is null)</li>
     * </ul>
     *
     * <p>Example path with collection operations:
     * <pre>
     *   Path: [User_.orders, Order_.items, Item_.price]
     *   CollectionOps: [
     *     {pathIndex=0, attribute=orders, selector=FIRST, specification=Order_.status.eq("ACTIVE")},
     *     {pathIndex=1, attribute=items, selector=ALL, specification=null}
     *   ]
     *   Result: Navigate to User.orders, take FIRST active order, then get ALL items, then get price from each
     * </pre>
     *
     * @param entity               The entity to start navigation from
     * @param path                 The path containing only MetaAttribute objects
     * @param collectionOperations Collection operation metadata for positions in the path (type-safe)
     * @return The value at the end of the path, or null if any intermediate value is null
     */
    Object getValueByPathWithCollections(
            T entity,
            java.util.List<MetaAttribute<?, ?>> path,
            java.util.List<com.thy.fss.common.inmemory.engine.mapping.CollectionOperationMetadata<?, ?>> collectionOperations
    );

    /**
     * Sets a value using a path that may contain collection operations.
     * Navigates through the path and sets the value at the target location.
     * Generated at build time with direct method calls (no reflection).
     * Type-safe: uses generic CollectionOperationMetadata for element type safety.
     *
     * <p>This method processes paths with collection operations for value assignment:
     * <ul>
     *   <li>Navigates to parent of final element using getValueByPathWithCollections()</li>
     *   <li>For each intermediate element, checks for collection operation</li>
     *   <li>If collection operation exists, applies it using extractFromCollection()</li>
     *   <li>If no collection operation, uses getFieldValue() for regular field access</li>
     *   <li>For final element, handles both simple field and collection assignment</li>
     * </ul>
     *
     * <p>Final element handling:
     * <ul>
     *   <li>ALL selector on final element: Adds value to collection</li>
     *   <li>FIRST/LAST/ANY selector on final element: Finds element and sets nested field</li>
     *   <li>No collection operation on final element: Sets field value directly</li>
     * </ul>
     *
     * <p>Example path with collection operations:
     * <pre>
     *   Path: [User_.orders, Order_.status]
     *   CollectionOps: [
     *     {pathIndex=0, attribute=orders, selector=FIRST, specification=Order_.id.eq(123)}
     *   ]
     *   Result: Navigate to User.orders, find FIRST order with id=123, then set status field
     * </pre>
     *
     * @param entity               The entity to start navigation from
     * @param path                 The path containing only MetaAttribute objects
     * @param collectionOperations Collection operation metadata for positions in the path (type-safe)
     * @param value                The value to set
     * @throws IllegalStateException if any intermediate value is null or target not found
     */
    void setValueByPathWithCollections(
            T entity,
            java.util.List<MetaAttribute<?, ?>> path,
            java.util.List<com.thy.fss.common.inmemory.engine.mapping.CollectionOperationMetadata<?, ?>> collectionOperations,
            Object value
    );

}