package com.thy.fss.common.inmemory.testmodel;

import com.thy.fss.common.inmemory.filter.CollectionFilter;
import com.thy.fss.common.inmemory.filter.EntityFilter;
import com.thy.fss.common.inmemory.filter.StringFilter;

/**
 * Manual filter class with CollectionFilter fields for testing web binding.
 * This filter is used to verify that the annotation processor generates correct
 * deserializer code for CollectionFilter fields with different element types.
 * 
 * Note: This is a manually created filter class (not generated by @MetaModel).
 * The annotation processor will generate a deserializer for this filter when
 * it processes the CollectionTestEntity class.
 */
public class CollectionTestFilter implements EntityFilter<CollectionTestEntity> {
    
    private StringFilter name;
    private CollectionFilter<String> tags;
    private CollectionFilter<Integer> scores;
    private CollectionFilter<Priority> priorities;
    
    public StringFilter getName() {
        return name;
    }
    
    public void setName(StringFilter name) {
        this.name = name;
    }
    
    public CollectionFilter<String> getTags() {
        return tags;
    }
    
    public void setTags(CollectionFilter<String> tags) {
        this.tags = tags;
    }
    
    public CollectionFilter<Integer> getScores() {
        return scores;
    }
    
    public void setScores(CollectionFilter<Integer> scores) {
        this.scores = scores;
    }
    
    public CollectionFilter<Priority> getPriorities() {
        return priorities;
    }
    
    public void setPriorities(CollectionFilter<Priority> priorities) {
        this.priorities = priorities;
    }
    
    @Override
    public Class<CollectionTestEntity> getEntityClass() {
        return CollectionTestEntity.class;
    }
}
