package com.thy.fss.common.inmemory.engine.sync;

import java.lang.reflect.Method;
import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import net.jqwik.api.Example;
import net.jqwik.api.Label;
import net.jqwik.api.lifecycle.AfterProperty;
import net.jqwik.api.lifecycle.BeforeProperty;

import com.thy.fss.common.inmemory.config.AggregationType;
import com.thy.fss.common.inmemory.datasource.BatchSnapshotEvent;
import com.thy.fss.common.inmemory.datasource.StreamingDataSource;
import com.thy.fss.common.inmemory.datasource.StreamingDataSourceState;
import com.thy.fss.common.inmemory.engine.analysis.AnalysisResult;
import com.thy.fss.common.inmemory.engine.mapping.MappingType;
import com.thy.fss.common.inmemory.engine.mapping.PropertyMapping;
import com.thy.fss.common.inmemory.entity.Identifiable;
import com.thy.fss.common.inmemory.factory.InMemorySpecStoreFactory;
import com.thy.fss.common.inmemory.specification.SpecificationServices;
import com.thy.fss.common.inmemory.specification.SpecificationService;
import com.thy.fss.common.inmemory.store.InMemoryDataStore;
import com.thy.fss.common.inmemory.testmodel.Customer;
import com.thy.fss.common.inmemory.testmodel.Customer_;
import com.thy.fss.common.inmemory.testmodel.Order;
import com.thy.fss.common.inmemory.testmodel.Order_;
import com.thy.fss.common.inmemory.testmodel.OrderItem;
import com.thy.fss.common.inmemory.testmodel.OrderItem_;

/**
 * Bug Condition Exploration Test — Store Mapping'lerin Entity'lere Uygulanmaması
 *
 * <p>Bu test, streaming pipeline'da (IncrementalSyncProcessor) store mapping'lerin
 * entity'lere hiçbir zaman uygulanmadığını kanıtlar. Phase 2 etkilenen mapping'leri
 * tespit eder ama uygulamaz. Phase 4 ham entity'leri store'lara yazar.</p>
 *
 * <p><b>BEKLENEN SONUÇ</b>: Bu testler fix'lenmemiş kodda BAŞARISIZ olmalıdır.
 * Başarısızlık, hatanın varlığını kanıtlar.</p>
 *
 * <p><b>Validates: Requirements 1.1, 1.2, 1.3, 1.4</b></p>
 */
class StoreMappingBugExplorationTest {

    private InMemorySpecStoreFactory factory;

    // ==================== MetaAttributes ====================

    // Use generated meta attributes from annotation processor (Customer_, Order_, OrderItem_)
    // These are the SAME instances used by the generated SpecificationService,
    // which compares by reference equality (==) in getFieldValue().

    // SpecificationServices (generated by @MetaModel annotation processor)
    @SuppressWarnings("unchecked")
    private static final SpecificationService<Customer> CUSTOMER_SPEC_SERVICE =
            (SpecificationService<Customer>) SpecificationServices.getService(Customer.class);
    @SuppressWarnings("unchecked")
    private static final SpecificationService<Order> ORDER_SPEC_SERVICE =
            (SpecificationService<Order>) SpecificationServices.getService(Order.class);
    @SuppressWarnings("unchecked")
    private static final SpecificationService<OrderItem> ORDER_ITEM_SPEC_SERVICE =
            (SpecificationService<OrderItem>) SpecificationServices.getService(OrderItem.class);

    // ==================== Setup / Teardown ====================

    @BeforeProperty
    void setUp() {
        factory = InMemorySpecStoreFactory.getInstance();
        factory.clearAll();
    }

    @AfterProperty
    void tearDown() {
        factory.clearAll();
    }

    // ==================== Helpers ====================

    @SuppressWarnings("unchecked")
    private <T extends Identifiable<?>> void registerReadyDatasource(String dsName) {
        StreamingDataSource<T> ds = mock(StreamingDataSource.class);
        when(ds.getName()).thenReturn(dsName);
        when(ds.getState()).thenReturn(StreamingDataSourceState.READY);
        factory.registerDataSource(dsName, ds);
    }

    private void registerStore(InMemoryDataStore<?> store) throws Exception {
        Method registerStore = InMemorySpecStoreFactory.class.getDeclaredMethod(
                "registerStore", InMemoryDataStore.class);
        registerStore.setAccessible(true);
        registerStore.invoke(factory, store);
    }

    // ==================== Test 1: ONE_TO_ONE Mapping ====================

    /**
     * ONE_TO_ONE: Customer.name should be populated from Order.status via FK mapping.
     *
     * <p>Scenario: Customer is the primary (store) entity. Order is the foreign entity.
     * Mapping: Order.status → Customer.name (via FK: Customer.id → Order.customerId).
     * When an Order arrives via streaming, the Customer's name field should be populated
     * from the matching Order's status field.</p>
     *
     * <p>Bug condition: storeMappings.size() > 0 AND datasource.state = READY AND changedEntities.size() > 0</p>
     * <p>Expected counterexample: Customer.name is null in store (mapping not applied)</p>
     *
     * <p><b>Validates: Requirements 1.1, 1.2</b></p>
     */
    @Example
    @Label("ONE_TO_ONE: Customer.name should be populated from Order.status — EXPECTED TO FAIL on unfixed code")
    void oneToOneMappingShouldPopulateMappedField() throws Exception {
        String customerDsName = "customer-ds";
        String orderDsName = "order-ds";
        String storeId = "customer-store";

        // Register datasources as READY
        registerReadyDatasource(customerDsName);
        registerReadyDatasource(orderDsName);

        // Register store for Customer entities
        InMemoryDataStore<Customer> store = new InMemoryDataStore<>(
                Customer.class, storeId, customerDsName, null, Collections.emptyList());
        registerStore(store);

        // ONE_TO_ONE mapping: Order.status → Customer.name
        // FK: Customer.id matches Order.customerId
        PropertyMapping<Customer, String> oneToOneMapping = PropertyMapping
                .<Customer, String>builder()
                .consumerId(storeId)
                .isForDashboard(false)
                .datasourceName(orderDsName)
                .mappingType(MappingType.ONE_TO_ONE)
                .sourcePath(List.of(Order_.status))
                .targetPath(List.of(Customer_.name))
                .primaryKeyPaths(List.of(List.of(Customer_.id)))
                .foreignKeyPaths(List.of(List.of(Order_.customerId)))
                .sourceService(ORDER_SPEC_SERVICE)
                .targetService(CUSTOMER_SPEC_SERVICE)
                .build();

        // Setup DependencyGraph with mapping
        DependencyGraph graph = new DependencyGraph();
        graph.addMapping(oneToOneMapping);

        // Pre-populate Order entity in DependencyGraph (foreign datasource)
        Order order = new Order();
        order.setId(100L);
        order.setCustomerId(1L);
        order.setStatus("CONFIRMED");
        graph.upsert(orderDsName, order);

        // Setup processor
        AnalysisResult analysisResult = new AnalysisResult(null, null, null);
        AtomicLong streamingVersion = new AtomicLong(0);
        IncrementalSyncProcessor processor = new IncrementalSyncProcessor(
                factory, graph, analysisResult, streamingVersion);

        // Send Customer entity via streaming event (primary entity)
        Customer customer = new Customer();
        customer.setId(1L);
        // name is null — should be populated by ONE_TO_ONE mapping from Order.status

        BatchSnapshotEvent<Customer> event = new BatchSnapshotEvent<>(List.of(customer), Instant.now());
        streamingVersion.incrementAndGet();
        processor.processBatchSnapshot(customerDsName, event);

        // ASSERT: Customer.name should be "CONFIRMED" (populated by ONE_TO_ONE mapping)
        // On unfixed code, this will be null — proving the bug exists
        List<Customer> storeData = store.findAll();
        assertThat(storeData).hasSize(1);

        Customer storedCustomer = storeData.get(0);
        assertThat(storedCustomer.getName())
                .as("ONE_TO_ONE Bug: Customer.name should be 'CONFIRMED' (from Order.status) but is null — "
                        + "Phase 2 detects the mapping but never applies it to the entity. "
                        + "Counterexample: Customer(id=1, name=null)")
                .isEqualTo("CONFIRMED");
    }

    // ==================== Test 2: MANY_TO_ONE_AGGREGATION COUNT ====================

    /**
     * MANY_TO_ONE_AGGREGATION COUNT: Customer.totalOrders should be populated with COUNT of Orders.
     *
     * <p>Scenario: Customer is the primary (store) entity. Order is the foreign entity.
     * Mapping: COUNT(Order[customerId=id]) → Customer.totalOrders.
     * When Orders arrive via streaming, the Customer's totalOrders field should be
     * populated with the count of matching Orders.</p>
     *
     * <p>Bug condition: storeMappings.size() > 0 AND datasource.state = READY AND changedEntities.size() > 0</p>
     * <p>Expected counterexample: Customer.totalOrders is null or 0 in store (aggregation not applied)</p>
     *
     * <p><b>Validates: Requirements 1.3, 1.4</b></p>
     */
    @Example
    @Label("MANY_TO_ONE_AGGREGATION COUNT: Customer.totalOrders should be 3 — EXPECTED TO FAIL on unfixed code")
    void aggregationCountMappingShouldPopulateCount() throws Exception {
        String customerDsName = "customer-ds";
        String orderDsName = "order-ds";
        String storeId = "customer-store";

        registerReadyDatasource(customerDsName);
        registerReadyDatasource(orderDsName);

        InMemoryDataStore<Customer> store = new InMemoryDataStore<>(
                Customer.class, storeId, customerDsName, null, Collections.emptyList());
        registerStore(store);

        // MANY_TO_ONE_AGGREGATION COUNT: COUNT(Order) → Customer.totalOrders
        // FK: Order.customerId matches Customer.id
        PropertyMapping<Customer, Integer> countMapping = PropertyMapping
                .<Customer, Integer>builder()
                .consumerId(storeId)
                .isForDashboard(false)
                .datasourceName(orderDsName)
                .mappingType(MappingType.MANY_TO_ONE_AGGREGATION)
                .aggregationType(AggregationType.COUNT)
                .targetPath(List.of(Customer_.totalOrders))
                .primaryKeyPaths(List.of(List.of(Customer_.id)))
                .foreignKeyPaths(List.of(List.of(Order_.customerId)))
                .sourceService(ORDER_SPEC_SERVICE)
                .targetService(CUSTOMER_SPEC_SERVICE)
                .build();

        DependencyGraph graph = new DependencyGraph();
        graph.addMapping(countMapping);

        // Pre-populate 3 Order entities for Customer id=1
        for (long i = 100; i < 103; i++) {
            Order order = new Order();
            order.setId(i);
            order.setCustomerId(1L);
            order.setTotalAmount(50.0);
            graph.upsert(orderDsName, order);
        }

        AnalysisResult analysisResult = new AnalysisResult(null, null, null);
        AtomicLong streamingVersion = new AtomicLong(0);
        IncrementalSyncProcessor processor = new IncrementalSyncProcessor(
                factory, graph, analysisResult, streamingVersion);

        // Send Customer entity
        Customer customer = new Customer();
        customer.setId(1L);
        customer.setTotalOrders(0); // default

        BatchSnapshotEvent<Customer> event = new BatchSnapshotEvent<>(List.of(customer), Instant.now());
        streamingVersion.incrementAndGet();
        processor.processBatchSnapshot(customerDsName, event);

        // ASSERT: Customer.totalOrders should be 3 (COUNT of 3 orders)
        // On unfixed code, this will be 0 — proving the bug exists
        List<Customer> storeData = store.findAll();
        assertThat(storeData).hasSize(1);

        Customer storedCustomer = storeData.get(0);
        assertThat(storedCustomer.getTotalOrders())
                .as("AGGREGATION COUNT Bug: Customer.totalOrders should be 3 but is 0 — "
                        + "Phase 2 detects the mapping but never applies the COUNT aggregation. "
                        + "Counterexample: Customer(id=1, totalOrders=0)")
                .isEqualTo(3);
    }

    // ==================== Test 3: MANY_TO_ONE_AGGREGATION SUM ====================

    /**
     * MANY_TO_ONE_AGGREGATION SUM: Customer.totalSpent should be populated with SUM of Order.totalAmount.
     *
     * <p>Scenario: Customer is the primary (store) entity. Order is the foreign entity.
     * Mapping: SUM(Order[customerId=id].totalAmount) → Customer.totalSpent.
     * This tests a different aggregation type to confirm the bug affects all aggregation types.</p>
     *
     * <p>Bug condition: storeMappings.size() > 0 AND datasource.state = READY AND changedEntities.size() > 0</p>
     * <p>Expected counterexample: Customer.totalSpent is null or 0.0 in store</p>
     *
     * <p><b>Validates: Requirements 1.3, 1.4</b></p>
     */
    @Example
    @Label("MANY_TO_ONE_AGGREGATION SUM: Customer.totalSpent should be 150.0 — EXPECTED TO FAIL on unfixed code")
    void aggregationSumMappingShouldPopulateSum() throws Exception {
        String customerDsName = "customer-ds";
        String orderDsName = "order-ds";
        String storeId = "customer-store";

        registerReadyDatasource(customerDsName);
        registerReadyDatasource(orderDsName);

        InMemoryDataStore<Customer> store = new InMemoryDataStore<>(
                Customer.class, storeId, customerDsName, null, Collections.emptyList());
        registerStore(store);

        // MANY_TO_ONE_AGGREGATION SUM: SUM(Order.totalAmount) → Customer.totalSpent
        PropertyMapping<Customer, Double> sumMapping = PropertyMapping
                .<Customer, Double>builder()
                .consumerId(storeId)
                .isForDashboard(false)
                .datasourceName(orderDsName)
                .mappingType(MappingType.MANY_TO_ONE_AGGREGATION)
                .aggregationType(AggregationType.SUM)
                .sourcePath(List.of(Order_.totalAmount))
                .targetPath(List.of(Customer_.totalSpent))
                .primaryKeyPaths(List.of(List.of(Customer_.id)))
                .foreignKeyPaths(List.of(List.of(Order_.customerId)))
                .sourceService(ORDER_SPEC_SERVICE)
                .targetService(CUSTOMER_SPEC_SERVICE)
                .build();

        DependencyGraph graph = new DependencyGraph();
        graph.addMapping(sumMapping);

        // Pre-populate 3 Order entities with totalAmount = 50.0 each
        for (long i = 100; i < 103; i++) {
            Order order = new Order();
            order.setId(i);
            order.setCustomerId(1L);
            order.setTotalAmount(50.0);
            graph.upsert(orderDsName, order);
        }

        AnalysisResult analysisResult = new AnalysisResult(null, null, null);
        AtomicLong streamingVersion = new AtomicLong(0);
        IncrementalSyncProcessor processor = new IncrementalSyncProcessor(
                factory, graph, analysisResult, streamingVersion);

        Customer customer = new Customer();
        customer.setId(1L);
        customer.setTotalSpent(0.0);

        BatchSnapshotEvent<Customer> event = new BatchSnapshotEvent<>(List.of(customer), Instant.now());
        streamingVersion.incrementAndGet();
        processor.processBatchSnapshot(customerDsName, event);

        // ASSERT: Customer.totalSpent should be 150.0 (SUM of 3 × 50.0)
        // On unfixed code, this will be 0.0 — proving the bug exists
        List<Customer> storeData = store.findAll();
        assertThat(storeData).hasSize(1);

        Customer storedCustomer = storeData.get(0);
        assertThat(storedCustomer.getTotalSpent())
                .as("AGGREGATION SUM Bug: Customer.totalSpent should be 150.0 but is 0.0 — "
                        + "Phase 2 detects the mapping but never applies the SUM aggregation. "
                        + "Counterexample: Customer(id=1, totalSpent=0.0)")
                .isEqualTo(150.0);
    }

    // ==================== Test 4: Composite Key Mapping ====================

    /**
     * Composite Key: Order.status should be populated via composite PK/FK mapping from OrderItem.
     *
     * <p>Scenario: Order is the primary (store) entity. OrderItem is the foreign entity.
     * Mapping uses composite key: (Order.id, Order.customerId) → (OrderItem.orderId, OrderItem.productId).
     * This tests that composite key mappings are also not applied in the streaming pipeline.</p>
     *
     * <p>Bug condition: storeMappings.size() > 0 AND datasource.state = READY AND changedEntities.size() > 0</p>
     * <p>Expected counterexample: Order.status is null in store (mapping not applied)</p>
     *
     * <p><b>Validates: Requirements 1.1, 1.2</b></p>
     */
    @Example
    @Label("Composite Key: ONE_TO_ONE with composite FK should populate mapped field — EXPECTED TO FAIL on unfixed code")
    void compositeKeyMappingShouldPopulateMappedField() throws Exception {
        String orderDsName = "order-ds";
        String itemDsName = "item-ds";
        String storeId = "order-store";

        registerReadyDatasource(orderDsName);
        registerReadyDatasource(itemDsName);

        InMemoryDataStore<Order> store = new InMemoryDataStore<>(
                Order.class, storeId, orderDsName, null, Collections.emptyList());
        registerStore(store);

        // ONE_TO_ONE mapping with composite key: OrderItem.unitPrice → Order.totalAmount
        // Composite FK: (Order.id, Order.customerId) → (OrderItem.orderId, OrderItem.productId)
        PropertyMapping<Order, Double> compositeMapping = PropertyMapping
                .<Order, Double>builder()
                .consumerId(storeId)
                .isForDashboard(false)
                .datasourceName(itemDsName)
                .mappingType(MappingType.ONE_TO_ONE)
                .sourcePath(List.of(OrderItem_.unitPrice))
                .targetPath(List.of(Order_.totalAmount))
                .primaryKeyPaths(List.of(
                        List.of(Order_.id),
                        List.of(Order_.customerId)))
                .foreignKeyPaths(List.of(
                        List.of(OrderItem_.orderId),
                        List.of(OrderItem_.productId)))
                .sourceService(ORDER_ITEM_SPEC_SERVICE)
                .targetService(ORDER_SPEC_SERVICE)
                .build();

        DependencyGraph graph = new DependencyGraph();
        graph.addMapping(compositeMapping);

        // Pre-populate OrderItem entity with matching composite key
        OrderItem item = new OrderItem();
        item.setId(1L);
        item.setOrderId(10L);      // matches Order.id
        item.setProductId(5L);      // matches Order.customerId
        item.setUnitPrice(99.99);
        graph.upsert(itemDsName, item);

        AnalysisResult analysisResult = new AnalysisResult(null, null, null);
        AtomicLong streamingVersion = new AtomicLong(0);
        IncrementalSyncProcessor processor = new IncrementalSyncProcessor(
                factory, graph, analysisResult, streamingVersion);

        // Send Order entity with matching composite key
        Order order = new Order();
        order.setId(10L);
        order.setCustomerId(5L);    // composite key part 2
        // totalAmount is null — should be populated by mapping from OrderItem.unitPrice

        BatchSnapshotEvent<Order> event = new BatchSnapshotEvent<>(List.of(order), Instant.now());
        streamingVersion.incrementAndGet();
        processor.processBatchSnapshot(orderDsName, event);

        // ASSERT: Order.totalAmount should be 99.99 (from OrderItem.unitPrice)
        // On unfixed code, this will be null — proving the bug exists
        List<Order> storeData = store.findAll();
        assertThat(storeData).hasSize(1);

        Order storedOrder = storeData.get(0);
        assertThat(storedOrder.getTotalAmount())
                .as("Composite Key Bug: Order.totalAmount should be 99.99 (from OrderItem.unitPrice) but is null — "
                        + "Phase 2 detects the mapping but never applies it. "
                        + "Counterexample: Order(id=10, customerId=5, totalAmount=null)")
                .isEqualTo(99.99);
    }
}
